version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=leonardo
      - POSTGRES_PASSWORD=leonardo
      - POSTGRES_DB=leonardo
    ports:
      - "5432:5432"
    volumes:
      - ./docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql   

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "leonardoavelar@terra.com.br"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "543:80"
    depends_on:
      - postgres